[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure content directory is accessible
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Handle dynamic routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server/:splat"
  status = 200
  force = false
