[build]
  command = "bun run build"
  publish = ".next/standalone"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./content/"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.30"

[[plugins]]
  package = "@netlify/plugin-nextjs"
