[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/videos"
  to = "/.netlify/functions/videos"
  status = 200

[[redirects]]
  from = "/api/videos/*"
  to = "/.netlify/functions/video-by-id"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

# Basic SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic authentication for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "admin:password"
