name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Copy CI environment file
        run: cp .env.ci .env
      - name: Setup database for tests
        run: npx prisma db push
      - name: Run tests
        run: NODE_ENV=test bun test --environment jsdom

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Copy CI environment file
        run: cp .env.ci .env
      - name: Setup database
        run: |
          npx prisma db push
          bun run seed
      - name: Install Cypress
        run: bun add -d cypress
      - name: Build app
        run: bun run build
      - name: Start app in background
        run: bun run start &
      - name: Wait for app to start
        run: npx wait-on http://localhost:3000 -t 60000
      - name: Run Cypress tests
        run: bun run cypress:run

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build Storybook
        run: bun run build-storybook
