name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Copy CI environment file
        run: cp .env.ci .env
      - name: Setup database for tests
        run: npx prisma db push
      - name: Run tests
        run: bun test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Copy CI environment file
        run: cp .env.ci .env
      - name: Setup database
        run: |
          npx prisma db push
          bun run seed
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: bun run build
          start: bun run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build Storybook
        run: bun run build-storybook
